+-/DataDescription: null
DataPreprocessing:
  Imputation: false
  Transformation: true
FeatureEngineering:
  FeatureScaling: false
  FeatureSelection: true
  FeatureTransformation: false
ModelEvalution:
  Classification: true
  Cluster: false
  Regression: true
  TSA: false
