+-/DataDescription: null
DataPreprocessing:
  Imputation: false
  Transformation: false
FeatureEngineering:
  FeatureScaling: false
  FeatureSelection: false
  FeatureTransformation: false
ModelEvalution:
  Classification: true
  Cluster: false
  Regression: false
  TSA: false
